name = "MolecularDynamicsIntegrators"
uuid = "293f545e-9dd2-11e9-1210-cf5bcdc9c322"
authors = ["Sunoru <s@sunoru.com>"]
version = "0.2.0"

[deps]
MosimoBase = "a39d5f18-f8b1-4777-8f97-f1f91469dbd0"

[compat]
julia = "1.7"
MosimoBase = "0.2"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
